spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://

  mail:
    host:
    port:
    username:
    password:

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
