spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://matheus:rjIEtacbYwJYsYma@mongo-db-study-tests.je9oz.mongodb.net/lp2?retryWrites=true&w=majority

  mail:
    host: localhost
    port: 25
    username: anything
    password: anything

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
