spring:
  data:
    mongodb:
      auto-index-creation: true
      uri:

  mail:
    host: locahost
    port: 25
    username: anything
    password: anything

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
